-- go-metin2 migration: 0005 item_template_state up
CREATE TABLE item_templates (
    vnum BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    stackable INTEGER NOT NULL DEFAULT 0,
    max_count INTEGER NOT NULL,
    shop_buy_price BIGINT NOT NULL DEFAULT 0,
    shop_sell_price BIGINT NOT NULL DEFAULT 0,
    refineable INTEGER NOT NULL DEFAULT 0,
    refine_reject_message TEXT NOT NULL DEFAULT '',
    save INTEGER NOT NULL DEFAULT 0,
    sell_count_per_gold INTEGER NOT NULL DEFAULT 0,
    slow_query INTEGER NOT NULL DEFAULT 0,
    highlight INTEGER NOT NULL DEFAULT 0,
    rare INTEGER NOT NULL DEFAULT 0,
    unique_item INTEGER NOT NULL DEFAULT 0,
    make_count INTEGER NOT NULL DEFAULT 0,
    irremovable INTEGER NOT NULL DEFAULT 0,
    confirm_when_use INTEGER NOT NULL DEFAULT 0,
    quest_use INTEGER NOT NULL DEFAULT 0,
    quest_use_multiple INTEGER NOT NULL DEFAULT 0,
    log INTEGER NOT NULL DEFAULT 0,
    applicable INTEGER NOT NULL DEFAULT 0,
    appearance_vnum BIGINT NOT NULL DEFAULT 0,
    anti_sell INTEGER NOT NULL DEFAULT 0,
    anti_drop INTEGER NOT NULL DEFAULT 0,
    anti_give INTEGER NOT NULL DEFAULT 0,
    anti_stack INTEGER NOT NULL DEFAULT 0,
    anti_get INTEGER NOT NULL DEFAULT 0,
    anti_male INTEGER NOT NULL DEFAULT 0,
    anti_female INTEGER NOT NULL DEFAULT 0,
    anti_warrior INTEGER NOT NULL DEFAULT 0,
    anti_assassin INTEGER NOT NULL DEFAULT 0,
    anti_sura INTEGER NOT NULL DEFAULT 0,
    anti_shaman INTEGER NOT NULL DEFAULT 0,
    anti_empire_a INTEGER NOT NULL DEFAULT 0,
    anti_empire_b INTEGER NOT NULL DEFAULT 0,
    anti_empire_c INTEGER NOT NULL DEFAULT 0,
    anti_save INTEGER NOT NULL DEFAULT 0,
    anti_pk_drop INTEGER NOT NULL DEFAULT 0,
    anti_myshop INTEGER NOT NULL DEFAULT 0,
    anti_safebox INTEGER NOT NULL DEFAULT 0,
    min_level INTEGER NOT NULL DEFAULT 0,
    equip_slot TEXT NOT NULL DEFAULT '',
    use_reject_message TEXT NOT NULL DEFAULT '',
    buy_reject_message TEXT NOT NULL DEFAULT '',
    drop_reject_message TEXT NOT NULL DEFAULT '',
    give_reject_message TEXT NOT NULL DEFAULT '',
    pickup_reject_message TEXT NOT NULL DEFAULT '',
    sell_reject_message TEXT NOT NULL DEFAULT '',
    equip_reject_message TEXT NOT NULL DEFAULT '',
    unequip_reject_message TEXT NOT NULL DEFAULT '',
    pickup_range INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (vnum > 0),
    CHECK (name <> ''),
    CHECK (stackable IN (0, 1)),
    CHECK (max_count > 0 AND max_count <= 255),
    CHECK (shop_buy_price >= 0 AND shop_buy_price <= 4294967295),
    CHECK (shop_sell_price >= 0 AND shop_sell_price <= 2147483647),
    CHECK (refineable IN (0, 1)),
    CHECK (save IN (0, 1)),
    CHECK (sell_count_per_gold IN (0, 1)),
    CHECK (slow_query IN (0, 1)),
    CHECK (highlight IN (0, 1)),
    CHECK (rare IN (0, 1)),
    CHECK (unique_item IN (0, 1)),
    CHECK (make_count IN (0, 1)),
    CHECK (irremovable IN (0, 1)),
    CHECK (confirm_when_use IN (0, 1)),
    CHECK (quest_use IN (0, 1)),
    CHECK (quest_use_multiple IN (0, 1)),
    CHECK (log IN (0, 1)),
    CHECK (applicable IN (0, 1)),
    CHECK (appearance_vnum >= 0 AND appearance_vnum <= 65535),
    CHECK (anti_sell IN (0, 1)),
    CHECK (anti_drop IN (0, 1)),
    CHECK (anti_give IN (0, 1)),
    CHECK (anti_stack IN (0, 1)),
    CHECK (anti_get IN (0, 1)),
    CHECK (anti_male IN (0, 1)),
    CHECK (anti_female IN (0, 1)),
    CHECK (anti_warrior IN (0, 1)),
    CHECK (anti_assassin IN (0, 1)),
    CHECK (anti_sura IN (0, 1)),
    CHECK (anti_shaman IN (0, 1)),
    CHECK (anti_empire_a IN (0, 1)),
    CHECK (anti_empire_b IN (0, 1)),
    CHECK (anti_empire_c IN (0, 1)),
    CHECK (anti_save IN (0, 1)),
    CHECK (anti_pk_drop IN (0, 1)),
    CHECK (anti_myshop IN (0, 1)),
    CHECK (anti_safebox IN (0, 1)),
    CHECK (min_level >= 0 AND min_level <= 255),
    CHECK (equip_slot IN ('', 'body', 'weapon', 'head', 'hair', 'shield', 'wrist', 'shoes', 'neck', 'ear', 'unique1', 'unique2', 'arrow')),
    CHECK (pickup_range >= 0 AND pickup_range <= 10000)
);

CREATE TABLE item_template_sockets (
    vnum BIGINT NOT NULL,
    position INTEGER NOT NULL,
    value INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (vnum, position),
    FOREIGN KEY (vnum) REFERENCES item_templates(vnum),
    CHECK (vnum > 0),
    CHECK (position >= 0 AND position < 3),
    CHECK (value >= -2147483648 AND value <= 2147483647)
);

CREATE TABLE item_template_attributes (
    vnum BIGINT NOT NULL,
    position INTEGER NOT NULL,
    type INTEGER NOT NULL,
    value INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (vnum, position),
    FOREIGN KEY (vnum) REFERENCES item_templates(vnum),
    CHECK (vnum > 0),
    CHECK (position >= 0 AND position < 7),
    CHECK (type > 0 AND type <= 255),
    CHECK (value >= -32768 AND value <= 32767)
);

CREATE TABLE item_template_use_effects (
    vnum BIGINT PRIMARY KEY,
    point_type INTEGER NOT NULL,
    point_index INTEGER NOT NULL,
    point_delta INTEGER NOT NULL,
    consume_count INTEGER NOT NULL DEFAULT 1,
    message TEXT NOT NULL,
    info_message TEXT NOT NULL DEFAULT '',
    special_effect_type INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vnum) REFERENCES item_templates(vnum),
    CHECK (vnum > 0),
    CHECK (point_type > 0 AND point_type <= 255),
    CHECK (point_index >= 0 AND point_index < 255),
    CHECK (point_delta <> 0 AND point_delta > -2147483648 AND point_delta <= 2147483647),
    CHECK (consume_count > 0 AND consume_count <= 255),
    CHECK (message <> ''),
    CHECK (special_effect_type >= 0 AND special_effect_type <= 25)
);

CREATE TABLE item_template_equip_effects (
    vnum BIGINT PRIMARY KEY,
    point_type INTEGER NOT NULL,
    point_index INTEGER NOT NULL,
    point_delta INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vnum) REFERENCES item_templates(vnum),
    CHECK (vnum > 0),
    CHECK (point_type > 0 AND point_type <= 255),
    CHECK (point_index >= 0 AND point_index < 255),
    CHECK (point_delta <> 0 AND point_delta > -2147483648 AND point_delta <= 2147483647)
);
